package com.sollink.docu.domain;

public class Compound {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String kind;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String prot;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String detaileddescription;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column COMPOUND.BASECOMPOUNDDEF
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String basecompounddef;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.ID
	 * @return  the value of COMPOUND.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.ID
	 * @param id  the value for COMPOUND.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.KIND
	 * @return  the value of COMPOUND.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getKind() {
		return kind;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.KIND
	 * @param kind  the value for COMPOUND.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setKind(String kind) {
		this.kind = kind;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.PROT
	 * @return  the value of COMPOUND.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getProt() {
		return prot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.PROT
	 * @param prot  the value for COMPOUND.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setProt(String prot) {
		this.prot = prot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.NAME
	 * @return  the value of COMPOUND.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.NAME
	 * @param name  the value for COMPOUND.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.DETAILEDDESCRIPTION
	 * @return  the value of COMPOUND.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getDetaileddescription() {
		return detaileddescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.DETAILEDDESCRIPTION
	 * @param detaileddescription  the value for COMPOUND.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setDetaileddescription(String detaileddescription) {
		this.detaileddescription = detaileddescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column COMPOUND.BASECOMPOUNDDEF
	 * @return  the value of COMPOUND.BASECOMPOUNDDEF
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getBasecompounddef() {
		return basecompounddef;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column COMPOUND.BASECOMPOUNDDEF
	 * @param basecompounddef  the value for COMPOUND.BASECOMPOUNDDEF
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setBasecompounddef(String basecompounddef) {
		this.basecompounddef = basecompounddef;
	}
}