package com.sollink.docu.domain;

public class Member {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.COMPOUND_ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String compoundId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String prot;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String kind;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.STATIC_PREFIX
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String staticPrefix;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.TYPE_NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String typeName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String detaileddescription;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column MEMBER.PARAMS
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private String params;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.ID
	 * @return  the value of MEMBER.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.ID
	 * @param id  the value for MEMBER.ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.COMPOUND_ID
	 * @return  the value of MEMBER.COMPOUND_ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getCompoundId() {
		return compoundId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.COMPOUND_ID
	 * @param compoundId  the value for MEMBER.COMPOUND_ID
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setCompoundId(String compoundId) {
		this.compoundId = compoundId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.PROT
	 * @return  the value of MEMBER.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getProt() {
		return prot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.PROT
	 * @param prot  the value for MEMBER.PROT
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setProt(String prot) {
		this.prot = prot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.KIND
	 * @return  the value of MEMBER.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getKind() {
		return kind;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.KIND
	 * @param kind  the value for MEMBER.KIND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setKind(String kind) {
		this.kind = kind;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.STATIC_PREFIX
	 * @return  the value of MEMBER.STATIC_PREFIX
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getStaticPrefix() {
		return staticPrefix;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.STATIC_PREFIX
	 * @param staticPrefix  the value for MEMBER.STATIC_PREFIX
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setStaticPrefix(String staticPrefix) {
		this.staticPrefix = staticPrefix;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.NAME
	 * @return  the value of MEMBER.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.NAME
	 * @param name  the value for MEMBER.NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.TYPE_NAME
	 * @return  the value of MEMBER.TYPE_NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.TYPE_NAME
	 * @param typeName  the value for MEMBER.TYPE_NAME
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.DETAILEDDESCRIPTION
	 * @return  the value of MEMBER.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getDetaileddescription() {
		return detaileddescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.DETAILEDDESCRIPTION
	 * @param detaileddescription  the value for MEMBER.DETAILEDDESCRIPTION
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setDetaileddescription(String detaileddescription) {
		this.detaileddescription = detaileddescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column MEMBER.PARAMS
	 * @return  the value of MEMBER.PARAMS
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getParams() {
		return params;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column MEMBER.PARAMS
	 * @param params  the value for MEMBER.PARAMS
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setParams(String params) {
		this.params = params;
	}
}