package com.sollink.docu.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MemberExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public MemberExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	protected MemberExample(MemberExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andCompoundIdIsNull() {
			addCriterion("COMPOUND_ID is null");
			return this;
		}

		public Criteria andCompoundIdIsNotNull() {
			addCriterion("COMPOUND_ID is not null");
			return this;
		}

		public Criteria andCompoundIdEqualTo(String value) {
			addCriterion("COMPOUND_ID =", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdNotEqualTo(String value) {
			addCriterion("COMPOUND_ID <>", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdGreaterThan(String value) {
			addCriterion("COMPOUND_ID >", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdGreaterThanOrEqualTo(String value) {
			addCriterion("COMPOUND_ID >=", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdLessThan(String value) {
			addCriterion("COMPOUND_ID <", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdLessThanOrEqualTo(String value) {
			addCriterion("COMPOUND_ID <=", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdLike(String value) {
			addCriterion("COMPOUND_ID like", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdNotLike(String value) {
			addCriterion("COMPOUND_ID not like", value, "compoundId");
			return this;
		}

		public Criteria andCompoundIdIn(List<String> values) {
			addCriterion("COMPOUND_ID in", values, "compoundId");
			return this;
		}

		public Criteria andCompoundIdNotIn(List<String> values) {
			addCriterion("COMPOUND_ID not in", values, "compoundId");
			return this;
		}

		public Criteria andCompoundIdBetween(String value1, String value2) {
			addCriterion("COMPOUND_ID between", value1, value2, "compoundId");
			return this;
		}

		public Criteria andCompoundIdNotBetween(String value1, String value2) {
			addCriterion("COMPOUND_ID not between", value1, value2,
					"compoundId");
			return this;
		}

		public Criteria andProtIsNull() {
			addCriterion("PROT is null");
			return this;
		}

		public Criteria andProtIsNotNull() {
			addCriterion("PROT is not null");
			return this;
		}

		public Criteria andProtEqualTo(String value) {
			addCriterion("PROT =", value, "prot");
			return this;
		}

		public Criteria andProtNotEqualTo(String value) {
			addCriterion("PROT <>", value, "prot");
			return this;
		}

		public Criteria andProtGreaterThan(String value) {
			addCriterion("PROT >", value, "prot");
			return this;
		}

		public Criteria andProtGreaterThanOrEqualTo(String value) {
			addCriterion("PROT >=", value, "prot");
			return this;
		}

		public Criteria andProtLessThan(String value) {
			addCriterion("PROT <", value, "prot");
			return this;
		}

		public Criteria andProtLessThanOrEqualTo(String value) {
			addCriterion("PROT <=", value, "prot");
			return this;
		}

		public Criteria andProtLike(String value) {
			addCriterion("PROT like", value, "prot");
			return this;
		}

		public Criteria andProtNotLike(String value) {
			addCriterion("PROT not like", value, "prot");
			return this;
		}

		public Criteria andProtIn(List<String> values) {
			addCriterion("PROT in", values, "prot");
			return this;
		}

		public Criteria andProtNotIn(List<String> values) {
			addCriterion("PROT not in", values, "prot");
			return this;
		}

		public Criteria andProtBetween(String value1, String value2) {
			addCriterion("PROT between", value1, value2, "prot");
			return this;
		}

		public Criteria andProtNotBetween(String value1, String value2) {
			addCriterion("PROT not between", value1, value2, "prot");
			return this;
		}

		public Criteria andKindIsNull() {
			addCriterion("KIND is null");
			return this;
		}

		public Criteria andKindIsNotNull() {
			addCriterion("KIND is not null");
			return this;
		}

		public Criteria andKindEqualTo(String value) {
			addCriterion("KIND =", value, "kind");
			return this;
		}

		public Criteria andKindNotEqualTo(String value) {
			addCriterion("KIND <>", value, "kind");
			return this;
		}

		public Criteria andKindGreaterThan(String value) {
			addCriterion("KIND >", value, "kind");
			return this;
		}

		public Criteria andKindGreaterThanOrEqualTo(String value) {
			addCriterion("KIND >=", value, "kind");
			return this;
		}

		public Criteria andKindLessThan(String value) {
			addCriterion("KIND <", value, "kind");
			return this;
		}

		public Criteria andKindLessThanOrEqualTo(String value) {
			addCriterion("KIND <=", value, "kind");
			return this;
		}

		public Criteria andKindLike(String value) {
			addCriterion("KIND like", value, "kind");
			return this;
		}

		public Criteria andKindNotLike(String value) {
			addCriterion("KIND not like", value, "kind");
			return this;
		}

		public Criteria andKindIn(List<String> values) {
			addCriterion("KIND in", values, "kind");
			return this;
		}

		public Criteria andKindNotIn(List<String> values) {
			addCriterion("KIND not in", values, "kind");
			return this;
		}

		public Criteria andKindBetween(String value1, String value2) {
			addCriterion("KIND between", value1, value2, "kind");
			return this;
		}

		public Criteria andKindNotBetween(String value1, String value2) {
			addCriterion("KIND not between", value1, value2, "kind");
			return this;
		}

		public Criteria andStaticPrefixIsNull() {
			addCriterion("STATIC_PREFIX is null");
			return this;
		}

		public Criteria andStaticPrefixIsNotNull() {
			addCriterion("STATIC_PREFIX is not null");
			return this;
		}

		public Criteria andStaticPrefixEqualTo(String value) {
			addCriterion("STATIC_PREFIX =", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixNotEqualTo(String value) {
			addCriterion("STATIC_PREFIX <>", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixGreaterThan(String value) {
			addCriterion("STATIC_PREFIX >", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixGreaterThanOrEqualTo(String value) {
			addCriterion("STATIC_PREFIX >=", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixLessThan(String value) {
			addCriterion("STATIC_PREFIX <", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixLessThanOrEqualTo(String value) {
			addCriterion("STATIC_PREFIX <=", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixLike(String value) {
			addCriterion("STATIC_PREFIX like", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixNotLike(String value) {
			addCriterion("STATIC_PREFIX not like", value, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixIn(List<String> values) {
			addCriterion("STATIC_PREFIX in", values, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixNotIn(List<String> values) {
			addCriterion("STATIC_PREFIX not in", values, "staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixBetween(String value1, String value2) {
			addCriterion("STATIC_PREFIX between", value1, value2,
					"staticPrefix");
			return this;
		}

		public Criteria andStaticPrefixNotBetween(String value1, String value2) {
			addCriterion("STATIC_PREFIX not between", value1, value2,
					"staticPrefix");
			return this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return this;
		}

		public Criteria andTypeNameIsNull() {
			addCriterion("TYPE_NAME is null");
			return this;
		}

		public Criteria andTypeNameIsNotNull() {
			addCriterion("TYPE_NAME is not null");
			return this;
		}

		public Criteria andTypeNameEqualTo(String value) {
			addCriterion("TYPE_NAME =", value, "typeName");
			return this;
		}

		public Criteria andTypeNameNotEqualTo(String value) {
			addCriterion("TYPE_NAME <>", value, "typeName");
			return this;
		}

		public Criteria andTypeNameGreaterThan(String value) {
			addCriterion("TYPE_NAME >", value, "typeName");
			return this;
		}

		public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE_NAME >=", value, "typeName");
			return this;
		}

		public Criteria andTypeNameLessThan(String value) {
			addCriterion("TYPE_NAME <", value, "typeName");
			return this;
		}

		public Criteria andTypeNameLessThanOrEqualTo(String value) {
			addCriterion("TYPE_NAME <=", value, "typeName");
			return this;
		}

		public Criteria andTypeNameLike(String value) {
			addCriterion("TYPE_NAME like", value, "typeName");
			return this;
		}

		public Criteria andTypeNameNotLike(String value) {
			addCriterion("TYPE_NAME not like", value, "typeName");
			return this;
		}

		public Criteria andTypeNameIn(List<String> values) {
			addCriterion("TYPE_NAME in", values, "typeName");
			return this;
		}

		public Criteria andTypeNameNotIn(List<String> values) {
			addCriterion("TYPE_NAME not in", values, "typeName");
			return this;
		}

		public Criteria andTypeNameBetween(String value1, String value2) {
			addCriterion("TYPE_NAME between", value1, value2, "typeName");
			return this;
		}

		public Criteria andTypeNameNotBetween(String value1, String value2) {
			addCriterion("TYPE_NAME not between", value1, value2, "typeName");
			return this;
		}

		public Criteria andDetaileddescriptionIsNull() {
			addCriterion("DETAILEDDESCRIPTION is null");
			return this;
		}

		public Criteria andDetaileddescriptionIsNotNull() {
			addCriterion("DETAILEDDESCRIPTION is not null");
			return this;
		}

		public Criteria andDetaileddescriptionEqualTo(String value) {
			addCriterion("DETAILEDDESCRIPTION =", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionNotEqualTo(String value) {
			addCriterion("DETAILEDDESCRIPTION <>", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionGreaterThan(String value) {
			addCriterion("DETAILEDDESCRIPTION >", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DETAILEDDESCRIPTION >=", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionLessThan(String value) {
			addCriterion("DETAILEDDESCRIPTION <", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionLessThanOrEqualTo(String value) {
			addCriterion("DETAILEDDESCRIPTION <=", value, "detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionLike(String value) {
			addCriterion("DETAILEDDESCRIPTION like", value,
					"detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionNotLike(String value) {
			addCriterion("DETAILEDDESCRIPTION not like", value,
					"detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionIn(List<String> values) {
			addCriterion("DETAILEDDESCRIPTION in", values,
					"detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionNotIn(List<String> values) {
			addCriterion("DETAILEDDESCRIPTION not in", values,
					"detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionBetween(String value1,
				String value2) {
			addCriterion("DETAILEDDESCRIPTION between", value1, value2,
					"detaileddescription");
			return this;
		}

		public Criteria andDetaileddescriptionNotBetween(String value1,
				String value2) {
			addCriterion("DETAILEDDESCRIPTION not between", value1, value2,
					"detaileddescription");
			return this;
		}

		public Criteria andParamsIsNull() {
			addCriterion("PARAMS is null");
			return this;
		}

		public Criteria andParamsIsNotNull() {
			addCriterion("PARAMS is not null");
			return this;
		}

		public Criteria andParamsEqualTo(String value) {
			addCriterion("PARAMS =", value, "params");
			return this;
		}

		public Criteria andParamsNotEqualTo(String value) {
			addCriterion("PARAMS <>", value, "params");
			return this;
		}

		public Criteria andParamsGreaterThan(String value) {
			addCriterion("PARAMS >", value, "params");
			return this;
		}

		public Criteria andParamsGreaterThanOrEqualTo(String value) {
			addCriterion("PARAMS >=", value, "params");
			return this;
		}

		public Criteria andParamsLessThan(String value) {
			addCriterion("PARAMS <", value, "params");
			return this;
		}

		public Criteria andParamsLessThanOrEqualTo(String value) {
			addCriterion("PARAMS <=", value, "params");
			return this;
		}

		public Criteria andParamsLike(String value) {
			addCriterion("PARAMS like", value, "params");
			return this;
		}

		public Criteria andParamsNotLike(String value) {
			addCriterion("PARAMS not like", value, "params");
			return this;
		}

		public Criteria andParamsIn(List<String> values) {
			addCriterion("PARAMS in", values, "params");
			return this;
		}

		public Criteria andParamsNotIn(List<String> values) {
			addCriterion("PARAMS not in", values, "params");
			return this;
		}

		public Criteria andParamsBetween(String value1, String value2) {
			addCriterion("PARAMS between", value1, value2, "params");
			return this;
		}

		public Criteria andParamsNotBetween(String value1, String value2) {
			addCriterion("PARAMS not between", value1, value2, "params");
			return this;
		}
	}
}