package com.sollink.docu.dao;

import com.sollink.docu.domain.Compound;
import com.sollink.docu.domain.CompoundExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CompoundDAOImpl extends SqlMapClientDaoSupport implements CompoundDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public CompoundDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void insert(Compound record) {
		getSqlMapClientTemplate().insert("COMPOUND.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByPrimaryKey(Compound record) {
		int rows = getSqlMapClientTemplate().update(
				"COMPOUND.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByPrimaryKeySelective(Compound record) {
		int rows = getSqlMapClientTemplate().update(
				"COMPOUND.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	@SuppressWarnings("unchecked")
	public List<Compound> selectByExample(CompoundExample example) {
		List<Compound> list = (List<Compound>) getSqlMapClientTemplate()
				.queryForList("COMPOUND.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public Compound selectByPrimaryKey(String id) {
		Compound key = new Compound();
		key.setId(id);
		Compound record = (Compound) getSqlMapClientTemplate().queryForObject(
				"COMPOUND.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int deleteByExample(CompoundExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"COMPOUND.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int deleteByPrimaryKey(String id) {
		Compound key = new Compound();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"COMPOUND.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int countByExample(CompoundExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"COMPOUND.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByExampleSelective(Compound record, CompoundExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"COMPOUND.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByExample(Compound record, CompoundExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"COMPOUND.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table COMPOUND
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private static class UpdateByExampleParms extends CompoundExample {
		private Object record;

		public UpdateByExampleParms(Object record, CompoundExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}