package com.sollink.docu.dao;

import com.sollink.docu.domain.Member;
import com.sollink.docu.domain.MemberExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MemberDAOImpl extends SqlMapClientDaoSupport implements MemberDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public MemberDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public void insert(Member record) {
		getSqlMapClientTemplate().insert("MEMBER.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByPrimaryKey(Member record) {
		int rows = getSqlMapClientTemplate().update(
				"MEMBER.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByPrimaryKeySelective(Member record) {
		int rows = getSqlMapClientTemplate().update(
				"MEMBER.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	@SuppressWarnings("unchecked")
	public List<Member> selectByExample(MemberExample example) {
		List<Member> list = (List<Member>) getSqlMapClientTemplate()
				.queryForList("MEMBER.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public Member selectByPrimaryKey(String id) {
		Member key = new Member();
		key.setId(id);
		Member record = (Member) getSqlMapClientTemplate().queryForObject(
				"MEMBER.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int deleteByExample(MemberExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"MEMBER.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int deleteByPrimaryKey(String id) {
		Member key = new Member();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"MEMBER.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int countByExample(MemberExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"MEMBER.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByExampleSelective(Member record, MemberExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MEMBER.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	public int updateByExample(Member record, MemberExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MEMBER.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	private static class UpdateByExampleParms extends MemberExample {
		private Object record;

		public UpdateByExampleParms(Object record, MemberExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}