package com.sollink.docu.dao;

import com.sollink.docu.domain.Member;
import com.sollink.docu.domain.MemberExample;
import java.util.List;

public interface MemberDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	void insert(Member record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int updateByPrimaryKey(Member record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	Member selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int countByExample(MemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int updateByExampleSelective(Member record, MemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table MEMBER
	 * @abatorgenerated  Fri Sep 19 17:02:23 KST 2008
	 */
	int updateByExample(Member record, MemberExample example);
}